GET http://localhost:5000/api/v1/user/

###
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
    "password": "quocthaideptrai",
    "phone": "0900000000"
}

###
POST http://localhost:5000/api/v1/auth/register
Content-Type: application/json

{
    "name": "teo",
    "password": "quocthaideptrai",
    "phone": "0900000000"
}